name: micro_home
description: "A new Flutter package project."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  lib_dependencies:
    git:
      url: https://github.com/danjho/lib-dependencies.git
  lib_core:
    git:
      url: https://github.com/danjho/lib-core.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
